name: ersaf_sampleapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.2.2
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logging: ^1.3.0
  meta: ^1.16.0
  oxidized: ^6.0.0
  path_provider: ^2.1.4
  shimmer: ^3.0.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/network.json